using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Logging.Abstractions;
using ChargeState.App.Services;
using ChargeState.App.ViewModels;
using ChargeState.Core.Infrastructure;
using ChargeState.Core.Panorama;
using ChargeState.Core.Processes;
using ChargeState.Core.Projects;
using ChargeState.Tests.TestSupport;

namespace ChargeState.Tests.Panorama;

/// <summary>A project's wiki page: reading and saving it on Panorama, and publishing it after changes.</summary>
public sealed class WikiTests
{
    private static readonly Uri Server = new("https://panoramaweb.org");

    /// <summary>The form of Panorama's wiki editor (captured from wiki-edit.view on panoramaweb.org, body shortened).</summary>
    private static string Editor(string body, int version = 18161) => $$"""
        <script type="text/javascript" nonce="b51d5557448bff2f">
            LABKEY._wiki.setProps({
                entityId: '9e9d2b09-a24f-103f-94c2-1cc91aa92d00',
                rowId: 4328,
                name: 'default',
                title: 'MNRF BioTRACK',
                body: '{{body}}',
                parent: null,
                pageVersionId: {{version}},
                rendererType: 'HTML',
                webPartId: 0,
                showAttachments: true,
                shouldIndex: true,
                isDirty: false,
                useVisualEditor: true
            });
            LABKEY._wiki.setAttachments([
            ]);
        </script>
        """;

    private const string HandWritten = @"\x3Cdiv style=\""max-width:1050px\""\x3E\n\x3Cp\x3EIt\'s 200 µL\x3C/p\x3E\x3C/div\x3E";

    private static string Ours(string hash) =>
        $@"\x3Cdiv\x3E\x3Cp\x3EProgress\x3C/p\x3E\n\x3Cdiv id=\""chargestate-wiki\"" data-written=\""{hash}\"" style=\""x\""\x3EGenerated by ChargeState\x3C/div\x3E\x3C/div\x3E";

    /// <summary>ChargeState's page with a fingerprint of the text above the footer that no longer matches it.</summary>
    private const string EditedOnPanorama =
        @"\x3Cdiv\x3E\x3Cp\x3EEdited by hand\x3C/p\x3E\n\x3Cdiv id=\""chargestate-wiki\"" data-written=\""abc\"" data-body=\""000000000000\""\x3EGenerated\x3C/div\x3E\x3C/div\x3E";

    private const string Runs = """
        {"rowCount":1,"rows":[{"FileName":"2026-09-BioTRACK-initial-plate1_2026-10-01_23-38-45.sky.zip","ReplicateCount":89,
         "PeptideCount":84806,"PeptideGroupCount":6746,"Created":"2026-10-01 23:42:20.311"}]}
        """;

    // -- Panorama ------------------------------------------------------------------------------

    [Fact]
    public void The_editor_gives_the_page_its_version_and_its_text()
    {
        var page = PanoramaClient.ParseWikiEditor(Editor(HandWritten));

        page.EntityId.ShouldBe("9e9d2b09-a24f-103f-94c2-1cc91aa92d00");
        (page.RowId, page.PageVersionId, page.Parent, page.Name, page.Title).ShouldBe((4328, 18161, (int?)null, "default", "MNRF BioTRACK"));
        page.Body.ShouldBe("<div style=\"max-width:1050px\">\n<p>It's 200 µL</p></div>");
        page.IsChargeState.ShouldBeFalse();
        page.WrittenHash.ShouldBeNull();

        var ours = PanoramaClient.ParseWikiEditor(Editor(Ours("3f2a9c01b7de")));
        ours.IsChargeState.ShouldBeTrue();
        ours.WrittenHash.ShouldBe("3f2a9c01b7de");
    }

    [Fact]
    public void An_editor_that_cannot_be_read_leaves_the_page_alone()
    {
        Should.Throw<PanoramaException>(() => PanoramaClient.ParseWikiEditor("<html>Sign in</html>")).Message.ShouldContain("left alone");
        Should.Throw<PanoramaException>(() => PanoramaClient.ParseWikiEditor("LABKEY._wiki.setProps({\n entityId: '',\n});"))
            .Message.ShouldContain("left alone");
    }

    [Fact]
    public void A_page_edited_on_Panorama_after_it_was_published_is_recognized()
    {
        const string above = "<div><p>Progress</p>\n";
        var hash = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(above)))[..12];
        static WikiPageInfo Page(string body) => new("e", 1, 2, "default", "T", body, null, true, true);
        var published = above + $"<div id=\"chargestate-wiki\" data-written=\"abc\" data-body=\"{hash}\">Generated</div>\n</div>\n";

        Page(published).EditedOnPanorama.ShouldBeFalse();
        Page(published.Replace("Progress", "Progress, and a sentence added on Panorama", StringComparison.Ordinal)).EditedOnPanorama.ShouldBeTrue();
        Page(above + "<div id=\"chargestate-wiki\" data-written=\"abc\">Generated</div>").EditedOnPanorama.ShouldBeFalse();  // before fingerprints
        Page("<p>by hand</p>").EditedOnPanorama.ShouldBeFalse();
    }

    [Theory]
    [InlineData(@"a\x3Cb\x3E", "a<b>")]
    [InlineData(@"µL – x", "µL – x")]
    [InlineData(@"it\'s \""q\"" \\ \/ \n", "it's \"q\" \\ / \n")]
    [InlineData(@"\xZZ", "xZZ")]
    public void JavaScript_strings_are_decoded(string literal, string text) =>
        PanoramaClient.DecodeJsString(literal).ShouldBe(text);

    [Fact]
    public void Skyline_documents_are_read_with_their_counts_and_upload_day()
    {
        var doc = PanoramaClient.ParseSkylineDocuments(Runs).Single();

        doc.ShouldBe(new SkylineDocument("2026-09-BioTRACK-initial-plate1", 89, 84806, 6746, new DateOnly(2026, 10, 1)));
        PanoramaClient.DocumentName("QC.sky.zip").ShouldBe("QC");
        PanoramaClient.DocumentName("plain.sky").ShouldBe("plain");
    }

    [Fact]
    public async Task A_page_that_does_not_exist_is_null_and_a_folder_with_spaces_is_encoded()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.NotFound));
        using var client = new PanoramaClient(Server, PanoramaCredential.ApiKey("k"), handler);

        (await client.GetWikiPageAsync("/MacCoss/Dog Aging", "default")).ShouldBeNull();
        handler.Requests.Single().RequestUri!.PathAndQuery.ShouldBe("/MacCoss/Dog%20Aging/wiki-edit.view?name=default");
    }

    /// <summary>Panorama's login-whoami.api: the session's CSRF token, and the session's cookies.</summary>
    private static HttpResponseMessage WhoAmI()
    {
        var response = Json("""{"id":1694,"displayName":"someone","CSRF":"t0k3n"}""");
        response.Headers.Add("Set-Cookie", "JSESSIONID=abc123; Path=/; Secure; HttpOnly");
        response.Headers.Add("Set-Cookie", "X-LABKEY-CSRF=t0k3n; Path=/; Secure");
        return response;
    }

    [Fact]
    public async Task Saving_names_the_version_it_replaces_and_reads_the_new_one()
    {
        var handler = new StubHandler(r => r.RequestUri!.AbsolutePath == "/login-whoami.api"
            ? WhoAmI()
            : Json("""{"success":true,"wikiProps":{"entityId":"9e9d","rowId":4328,"pageVersionId":18200}}"""));
        using var client = new PanoramaClient(Server, PanoramaCredential.ApiKey("k"), handler);
        var existing = PanoramaClient.ParseWikiEditor(Editor(HandWritten));

        var saved = await client.SaveWikiPageAsync("/MacCoss/Collaborations/MNRF/BioTRACK", "default", "MNRF BioTRACK", "<div>new</div>", existing);

        saved.PageVersionId.ShouldBe(18200);
        // LabKey wants a CSRF token on a POST, even with an API key: it comes from whoami, with the session's cookies.
        handler.Requests.Select(r => r.Method.Method).ShouldBe(["GET", "POST"]);
        var request = handler.Requests[1];
        request.Headers.GetValues("X-LABKEY-CSRF").Single().ShouldBe("t0k3n");
        request.Headers.GetValues("Cookie").Single().ShouldBe("JSESSIONID=abc123; X-LABKEY-CSRF=t0k3n");
        request.Headers.Authorization.ShouldNotBeNull();
        request.Method.ShouldBe(HttpMethod.Post);
        request.RequestUri!.AbsolutePath.ShouldBe("/MacCoss/Collaborations/MNRF/BioTRACK/wiki-saveWiki.api");
        var sent = handler.Bodies.Single();
        sent.GetProperty("entityId").GetString().ShouldBe("9e9d2b09-a24f-103f-94c2-1cc91aa92d00");
        sent.GetProperty("pageVersionId").GetInt32().ShouldBe(18161);
        sent.GetProperty("rendererType").GetString().ShouldBe("HTML");
        sent.GetProperty("body").GetString().ShouldBe("<div>new</div>");
    }

    [Fact]
    public async Task A_new_page_is_saved_without_an_id_and_a_refusal_says_why()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.BadRequest)
        {
            Content = new StringContent("""{"exception":"Someone else has edited this page since you started.","success":false}"""),
        });
        using var client = new PanoramaClient(Server, PanoramaCredential.ApiKey("k"), handler);

        var ex = await Should.ThrowAsync<PanoramaException>(() => client.SaveWikiPageAsync("/MacCoss/x", "default", "T", "<p/>", null));

        ex.Message.ShouldBe("Panorama refused the wiki page default in /MacCoss/x: Someone else has edited this page since you started.");
        handler.Bodies.Single().GetProperty("entityId").ValueKind.ShouldBe(JsonValueKind.Null);
        handler.Bodies.Single().GetProperty("name").GetString().ShouldBe("default");
    }

    // -- the app -------------------------------------------------------------------------------

    [Theory]
    [InlineData("/MacCoss/Collaborations/MNRF/BioTRACK", "/MacCoss/Collaborations/MNRF/BioTRACK/2026-09-BioTRACK-Quant/@files/RawFiles",
        "/MacCoss/Collaborations/MNRF/BioTRACK/2026-09-BioTRACK-Quant", "/MacCoss/Collaborations/MNRF/BioTRACK/2026-09-BioTRACK-Control")]
    [InlineData("/MacCoss/maccoss/2026-Marten", "/MacCoss/maccoss/@files/2026-Marten", "/MacCoss/maccoss/2026-Marten")]
    [InlineData(null, "/MacCoss/maccoss/@files/2026-Marten")]
    [InlineData("/MacCoss/Collaborations/Zoo", "/MacCoss/Collaborations/Zoo/Marten-DIA")]
    [InlineData(null)]
    public void The_suggested_folder_holds_the_experiments_folders(string? suggested, params string[] folders)
    {
        var project = new ProjectSummary
        {
            Project = "P",
            Experiments = [new ExperimentSummary { Experiment = "2026-09-X", Panorama = [.. folders.Select(f => new PanoramaFolder(f, "raw"))] }],
        };

        WikiPublisher.SuggestFolder(project).ShouldBe(suggested);
    }

    [Fact]
    public void The_window_says_what_publishing_would_do()
    {
        var content = new WikiPageContent("P", "/MacCoss/x", "default", "T", "<div/>", Written: true, WrittenHash: "abc");
        var ours = PanoramaClient.ParseWikiEditor(Editor(Ours("abc")));

        WikiViewModel.Describe(false, null, content).ShouldStartWith("Not signed in to Panorama");
        WikiViewModel.Describe(true, null, content).ShouldStartWith("Not on Panorama yet.");
        WikiViewModel.Describe(true, PanoramaClient.ParseWikiEditor(Editor(HandWritten)), content).ShouldContain("written by hand");
        WikiViewModel.Describe(true, ours, content).ShouldBe("On Panorama, and updated by the app after every change.");
        WikiViewModel.Describe(true, ours, content with { WrittenHash = "def" }).ShouldContain("The text has changed");
        WikiViewModel.Describe(true, ours, content with { Written = false }).ShouldContain("Write the text with Claude");
        WikiViewModel.Describe(true, PanoramaClient.ParseWikiEditor(Editor(EditedOnPanorama)), content).ShouldContain("was edited there");
        WikiViewModel.Document("<p>x</p>", "https://panoramaweb.org/MacCoss/x/wiki-page.view?name=default")
            .ShouldContain("<base href=\"https://panoramaweb.org/MacCoss/x/wiki-page.view?name=default\">");
    }

    [Fact]
    public async Task After_a_change_the_app_updates_its_own_page_with_the_Skyline_documents()
    {
        using var setup = new Publisher(Editor(Ours("abc")), hash: "abc");

        var notice = await setup.Wiki.UpdateAsync(setup.Project);

        notice.ShouldNotBeNull().ShouldStartWith("Wiki page for MNRF-BioTRACK updated");
        var save = setup.Handler.Bodies.Single();
        save.GetProperty("pageVersionId").GetInt32().ShouldBe(18161);
        save.GetProperty("body").GetString().ShouldBe(setup.Html);
        // The results folder's documents went to the engine.
        setup.Documents.ShouldContain("2026-09-BioTRACK-initial-plate1");
        setup.Documents.ShouldContain("\"replicates\":89");
    }

    [Fact]
    public async Task A_page_written_by_hand_or_new_text_waits_for_a_person()
    {
        using (var handWritten = new Publisher(Editor(HandWritten), hash: "abc"))
        {
            (await handWritten.Wiki.UpdateAsync(handWritten.Project)).ShouldBeNull();
            handWritten.Handler.Bodies.ShouldBeEmpty();
        }

        using (var newText = new Publisher(Editor(Ours("abc")), hash: "def"))
        {
            (await newText.Wiki.UpdateAsync(newText.Project)).ShouldNotBeNull().ShouldContain("open Wiki page to review and publish it");
            newText.Handler.Bodies.ShouldBeEmpty();
        }

        using (var edited = new Publisher(Editor(EditedOnPanorama), hash: "abc"))
        {
            (await edited.Wiki.UpdateAsync(edited.Project)).ShouldNotBeNull().ShouldContain("edited on Panorama since the app published it");
            edited.Handler.Bodies.ShouldBeEmpty();
        }

        using var missing = new Publisher(editor: null, hash: "abc");
        (await missing.Wiki.UpdateAsync(missing.Project)).ShouldBeNull();
        missing.Handler.Bodies.ShouldBeEmpty();
    }

    [Fact]
    public async Task Without_a_working_sign_in_nothing_is_sent_and_the_person_is_told()
    {
        using var setup = new Publisher(Editor(Ours("abc")), hash: "abc", signedIn: false);

        (await setup.Wiki.UpdateAsync(setup.Project)).ShouldNotBeNull().ShouldContain("no Panorama sign-in works");
        setup.Handler.Bodies.ShouldBeEmpty();
    }

    private static HttpResponseMessage Json(string body) =>
        new(HttpStatusCode.OK) { Content = new StringContent(body, Encoding.UTF8, "application/json") };

    /// <summary>A WikiPublisher whose Panorama and engine answer from here.</summary>
    private sealed class Publisher : IDisposable
    {
        private readonly TempDirectory _dir = new();

        public Publisher(string? editor, string hash, bool signedIn = true)
        {
            Html = $"<div><p>Progress</p>\n<div id=\"chargestate-wiki\" data-written=\"{hash}\">Generated</div></div>\n";
            Handler = new StubHandler(request => request.RequestUri!.AbsolutePath switch
            {
                "/_webdav/" => Json("""{"files":[]}"""),
                "/login-whoami.api" => WhoAmI(),
                var p when p.EndsWith("/wiki-edit.view", StringComparison.Ordinal) =>
                    editor is null ? new HttpResponseMessage(HttpStatusCode.NotFound) : new HttpResponseMessage(HttpStatusCode.OK) { Content = new StringContent(editor) },
                var p when p.EndsWith("/query-selectRows.api", StringComparison.Ordinal) => Json(Runs),
                var p when p.EndsWith("/wiki-saveWiki.api", StringComparison.Ordinal) => Json("""{"success":true,"wikiProps":{"pageVersionId":18200}}"""),
                _ => new HttpResponseMessage(HttpStatusCode.NotFound),
            });
            var store = new Store();
            if (signedIn)
            {
                store.Entries["PanoramaBridge:https://panoramaweb.org"] = new StoredCredential("apikey", "k");
            }

            Directory.CreateDirectory(Path.Combine(_dir.Path, "tools"));
            File.WriteAllText(Path.Combine(_dir.Path, "tools", "uv.exe"), "");
            var engine = new ProjectEngine(new Runner(this, hash), new ToolLocator(_dir.Path)) { RepositoryPath = _dir.Path };
            Wiki = new WikiPublisher(new PanoramaSignIn(store, Server), engine, new WorkTracker(NullLogger<WorkTracker>.Instance),
                new AppPaths(_dir.Path), NullLogger<WikiPublisher>.Instance) { Handler = Handler };
        }

        public StubHandler Handler { get; }

        public WikiPublisher Wiki { get; }

        public string Html { get; }

        /// <summary>The --documents JSON the engine was given.</summary>
        public string Documents { get; set; } = "";

        public ProjectSummary Project { get; } = new()
        {
            Project = "MNRF-BioTRACK",
            Wiki = new WikiLocation("/MacCoss/Collaborations/MNRF/BioTRACK", "default"),
            Experiments =
            [
                new ExperimentSummary
                {
                    Experiment = "2026-09-BioTRACK-DIA", Status = "active",
                    Panorama =
                    [
                        new PanoramaFolder("/MacCoss/Collaborations/MNRF/BioTRACK/2026-09-BioTRACK-Quant/@files/RawFiles", "raw"),
                        new PanoramaFolder("/MacCoss/Collaborations/MNRF/BioTRACK/2026-09-BioTRACK-Quant", "results"),
                    ],
                },
            ],
        };

        public void Dispose() => _dir.Dispose();

        private sealed class Runner(Publisher owner, string hash) : IProcessRunner
        {
            public Task<ProcessResult> RunAsync(
                string fileName, IEnumerable<string> arguments, string? workingDirectory = null,
                IReadOnlyDictionary<string, string?>? environment = null, TimeSpan? timeout = null,
                CancellationToken cancellationToken = default)
            {
                var args = arguments.ToList();
                var documents = args.IndexOf("--documents");
                if (documents >= 0)
                {
                    owner.Documents = File.ReadAllText(args[documents + 1]);
                }

                var json = JsonSerializer.Serialize(new
                {
                    ok = true, project = "MNRF-BioTRACK", folder = "/MacCoss/Collaborations/MNRF/BioTRACK", page = "default",
                    title = "MNRF BioTRACK", html = owner.Html, written = true, written_hash = hash,
                });
                return Task.FromResult(new ProcessResult(0, json, ""));
            }
        }
    }

    private sealed class Store : ICredentialStore
    {
        public Dictionary<string, StoredCredential> Entries { get; } = [];

        public StoredCredential? Read(string target) => Entries.TryGetValue(target, out var c) ? c : null;

        public void Write(string target, StoredCredential credential, string comment) => Entries[target] = credential;

        public void Delete(string target) => Entries.Remove(target);
    }

    private sealed class StubHandler(Func<HttpRequestMessage, HttpResponseMessage> respond) : HttpMessageHandler
    {
        public List<HttpRequestMessage> Requests { get; } = [];

        /// <summary>The JSON of each POST.</summary>
        public List<JsonElement> Bodies { get; } = [];

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            Requests.Add(request);
            if (request.Content is not null)
            {
                Bodies.Add(JsonDocument.Parse(await request.Content.ReadAsStringAsync(cancellationToken)).RootElement.Clone());
            }

            return respond(request);
        }
    }
}
