using LabOps.Core.Infrastructure;
using LabOps.Core.Panorama;
using LabOps.Tests.TestSupport;

namespace LabOps.Tests.App;

/// <summary>The app was ChargeState until 26.7.0: what LabOps takes over, and what it still recognizes.</summary>
public sealed class RenameTests
{
    [Fact]
    public void The_first_start_takes_over_ChargeStates_settings_and_sessions_but_not_its_logs()
    {
        using var dir = new TempDirectory();
        var legacy = dir.Combine("ChargeState");
        Directory.CreateDirectory(Path.Combine(legacy, "claude", "MNRF-BioTRACK"));
        Directory.CreateDirectory(Path.Combine(legacy, "logs"));
        File.WriteAllText(Path.Combine(legacy, "settings.json"), """{"ProjectsRepositoryPath":"D:\\lab-projects"}""");
        File.WriteAllText(Path.Combine(legacy, "claude", "MNRF-BioTRACK", "mcp.json"), "{}");
        File.WriteAllText(Path.Combine(legacy, "logs", "chargestate-20261004.log"), "old log");
        var paths = new AppPaths(dir.Combine("LabOps"));
        paths.EnsureCreated();

        paths.AdoptLegacy(legacy).ShouldBeTrue();

        File.ReadAllText(paths.SettingsFile).ShouldContain("lab-projects");
        new SettingsStore(paths.SettingsFile).Load().ProjectsRepositoryPath.ShouldBe(@"D:\lab-projects");
        File.Exists(Path.Combine(paths.SessionDirectory, "MNRF-BioTRACK", "mcp.json")).ShouldBeTrue();
        Directory.EnumerateFiles(paths.LogDirectory).ShouldBeEmpty();
        File.Exists(Path.Combine(legacy, "settings.json")).ShouldBeTrue();  // copied, so ChargeState still works

        // Only once: LabOps' own settings are never replaced.
        File.WriteAllText(Path.Combine(legacy, "settings.json"), """{"ProjectsRepositoryPath":"elsewhere"}""");
        paths.AdoptLegacy(legacy).ShouldBeFalse();
        new SettingsStore(paths.SettingsFile).Load().ProjectsRepositoryPath.ShouldBe(@"D:\lab-projects");
    }

    [Fact]
    public void Without_ChargeState_there_is_nothing_to_take_over()
    {
        using var dir = new TempDirectory();
        var paths = new AppPaths(dir.Combine("LabOps"));
        paths.EnsureCreated();

        paths.AdoptLegacy(dir.Combine("ChargeState")).ShouldBeFalse();
        File.Exists(paths.SettingsFile).ShouldBeFalse();
    }

    [Fact]
    public void A_wiki_page_published_as_ChargeState_is_still_the_apps_to_update()
    {
        var page = new WikiPageInfo("e", 1, 2, "default", "MNRF BioTRACK",
            "<div><p>Progress</p>\n<div id=\"chargestate-wiki\" data-written=\"5b8ecc811ec6\" style=\"x\">Generated by ChargeState</div>\n</div>\n",
            null, true, true);

        page.IsLabOps.ShouldBeTrue();
        page.WrittenHash.ShouldBe("5b8ecc811ec6");
        page.EditedOnPanorama.ShouldBeFalse();
    }

    [Fact]
    public void LabOps_has_its_own_package_and_update_channels()
    {
        AppInfo.ProductName.ShouldBe("LabOps");
        AppInfo.PackageId.ShouldBe("MacCossLab.LabOps");
        AppInfo.LegacyPackageId.ShouldBe("MacCossLab.ChargeState");
        (AppInfo.UpdateChannel, AppInfo.BetaUpdateChannel).ShouldBe(("stable", "beta"));
        // ChargeState's were win and win-beta; sharing one would let it take a LabOps release for its own.
        new[] { AppInfo.UpdateChannel, AppInfo.BetaUpdateChannel }.ShouldNotContain("win");
        new[] { AppInfo.UpdateChannel, AppInfo.BetaUpdateChannel }.ShouldNotContain("win-beta");
    }
}
